articles/urls.py
from django.urls import path
from . import views
from Django.views import about

app_name="articles"
urlpatterns = [
    path('',views.article_list,name="list"),
    path('<slug>',views.article_detail,name="detail")
]

untitled/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Django import views
from Django.views import about


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/',views.about),
    path('',views.home),
    path('articles/',include('articles.urls')),
]
urlpatterns+= staticfiles_urlpatterns()

Django/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(max_length=100)
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50]+' ...'

Django/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
def about(request):
        return render(request,'about.html')
def home(request):
        return render(request,'home.html')

articles/views.py
from django.shortcuts import render,HttpResponse
from . import models

def article_list(request):
        articles=models.Article.objects.all().order_by('date')
        return render(request,'articles/articlelist.html',{'articles':articles})
def article_detail(request,slug):
        return HttpResponse(slug)

articles/templates/articles/articlelist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>s
    <meta charset="UTF-8">
    <title>articles</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<h1>Article List</h1>
{% for article in articles %}
    <h2 style="color: red;font-size: 25px;"><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a> </h2>
    <p>{{ article.snippet }}</p>
    <p>{{ article.date }}</p>
{% endfor %}

</body>
</html>

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
<h1>About</h1>
<p>ما جنگو رو دوست داریم</p>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<h1>Home</h1>
<p>Welcome to Blog</p>
</body>
</html>